### ISSUE TITLE
Builds on Windows runner failing after e7d3dad

### ISSUE THREAD

**Issue by MitsCommitch** [Nuitka/Nuitka-Action#20]
Getting the following logs on my builds with this action since e7d3dad:
```
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:8e[5](https://github.com/MitsCommitch/lexecution/actions/runs/4969853546/jobs/8893339162#step:1:5)e7e5ab8b370d[6](https://github.com/MitsCommitch/lexecution/actions/runs/4969853546/jobs/8893339162#step:1:7)c329ec48022[13](https://github.com/MitsCommitch/lexecution/actions/runs/4969853546/jobs/8893339162#step:1:16)32ada57f0ab)
Download action repository 'actions/setup-python@v4' (SHA:57ded4d7d5e986d7296eab16560982c6dd7c923b)
Download action repository 'Nuitka/Nuitka-Action@main' (SHA:e7d3dad06b9af01972acd6d2feed829bba455d26)
Download action repository 'actions/upload-artifact@v3' (SHA:0b7f8abb1508[18](https://github.com/MitsCommitch/lexecution/actions/runs/4969853546/jobs/8893339162#step:1:22)[19](https://github.com/MitsCommitch/lexecution/actions/runs/4969853546/jobs/8893339162#step:1:23)56e8e162db84b466c27e18ce)
Error: Nuitka\Nuitka-Action\main\action.yml (Line: [21](https://github.com/MitsCommitch/lexecution/actions/runs/4969853546/jobs/8893339162#step:1:25)9, Col: 12):
Error: Nuitka\Nuitka-Action\main\action.yml (Line: 219, Col: 12): Unrecognized named-value: 'macos-target-arch'. Located at position 1 within expression: macos-target-arch
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. Nuitka\Nuitka-Action\main\action.yml (Line: 219, Col: 12): Unrecognized named-value: 'macos-target-arch'. Located at position 1 within expression: macos-target-arch
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load Nuitka\Nuitka-Action\main\action.yml 
```

Judging by the format, it looks like a small error in referencing template inputs. possible fix PR to follow.

**Comment by MitsCommitch** [comment]
Added #21 with a possible resolution

**Comment by kayhayen** [comment]
Merged. We need automatic tests for main really.

**Comment by XBigTK13X** [comment]
As I mentioned in a comment on that patch, the patch will fix the problem in this issue but there was a typo in the patch. Until that small typo is fixed then the issue persists.

**Comment by kayhayen** [comment]
I think I merged a PR that fixes it too.
