### ISSUE TITLE
Build fails with pyside

### ISSUE THREAD

**Issue by janvorac** [Nuitka/Nuitka-Action#41]
```
"C:\Program Files\Git\usr\bin\tar.exe" -xf D:/a/_temp/20af7276-e250-4e04-b69f-df8720fa5665/cache.tzst -P -C D:/a/lighterOES/lighterOES --force-local --use-compress-program "zstd -d"
Cache restored successfully
Cache restored from key: Windows-python-3.10-nuitka-64abde58319c52f93cb80f06872172b91046f318
Run set -e
Nuitka-Options:INFO: Used command line options: --onefile --standalone --assume-yes-for-downloads --output-dir=build --script-name=src/main_window.py --enable-plugins=pyside6
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\plugins\Plugins.py", line 82, in withPluginProblemReporting
    yield
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\plugins\Plugins.py", line 123, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 1419, in __init__
    NuitkaPluginQtBindingsPluginBase.__init__(
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 65, in __init__
    self.distribution = getDistributionFromModuleName(self.binding_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\utils\Distributions.py", line 212, in getDistributionFromModuleName
    distributions = getDistributionsFromModuleName(module_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\utils\Distributions.py", line 198, in getDistributionsFromModuleName
    and module_name.getPackageName() is not None
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'getPackageName'
FATAL: pyside6: Plugin issue while working on 'Plugin initialization failed'. Please report the bug with the above traceback included.
Error: Process completed with exit code 1.
```

**Comment by kayhayen** [comment]
Nuitka-Action is not the right repo for bugs with Nuitka, I am transferring it.
