### ISSUE TITLE
Tkinter plugin erroring. Works fine on regular Nuitka.

### ISSUE THREAD

**Issue by Jaxx7594** [Nuitka/Nuitka-Action#46]
I did see #37, but it actually is a Nuitka Options issue. I don't get any errors when running the exact same command on my computer, it only errors when using Nuitka Options to compile. Heres my action yml: https://github.com/Jaxx7594/test-python-script-to-exe/blob/main/.github/workflows/test.yml. I also tested enable-plugin***s*** as shown in the examples instead of enable-plugin, and it simply does nothing. The plugin isn't enabled, and the tcl files aren't included.
```
Nuitka-Options: Used command line options: --standalone --disable-console --enable-plugin=tk-inter --windows-icon-from-ico=images/icon.png --remove-output --mingw64 --assume-yes-for-downloads --output-dir=build --script-name=main.py
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.8\x64\Lib\site-packages\nuitka\plugins\Plugins.py", line 82, in withPluginProblemReporting
    yield
  File "C:\hostedtoolcache\windows\Python\3.11.8\x64\Lib\site-packages\nuitka\plugins\Plugins.py", line 123, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NuitkaPluginTkinter.__init__() missing 2 required positional arguments: 'tcl_library_dir' and 'tk_library_dir'
FATAL: tk-inter: Plugin issue while working on 'Plugin initialization failed'. Please report the bug with the above traceback included.
Error: Process completed with exit code 1.
```

**Comment by kayhayen** [comment]
That's not good, these plugins are not required, and that would be bug of the options parsing. I will try and get it emulated.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.
